---
  - name: check param VAR_Zabbix40_Server_linux_extracting_rolename is none
    fail:
      msg: "Parameter VAR_Zabbix40_Server_linux_extracting_rolename cannot be NULL."
    when: "(VAR_Zabbix40_Server_linux_extracting_rolename is none) or (VAR_Zabbix40_Server_linux_extracting_rolename == '')"

  - name: check param VAR_Zabbix40_Server_linux_gathering_dest
    fail:
      msg: "Parameter VAR_Zabbix40_Server_linux_gathering_dest cannot be NULL."
    when: "(VAR_Zabbix40_Server_linux_gathering_dest is none) or (VAR_Zabbix40_Server_linux_gathering_dest == '')"

  - name: check param VAR_Zabbix40_Server_linux_extracting_dest
    fail:
      msg: "Parameter VAR_Zabbix40_Server_linux_extracting_dest cannot be NULL."
    when: "(VAR_Zabbix40_Server_linux_extracting_dest is none) or (VAR_Zabbix40_Server_linux_extracting_dest == '')"

  - name: Remove old data
    file:
      path: "{{ VAR_Zabbix40_Server_linux_extracting_dest }}/{{ inventory_hostname }}/{{ item }}.yml"
      state: absent
    with_items: "{{ VAR_Zabbix40_Server_linux_extracting_rolename }}"
    delegate_to: localhost
    become: no

  - name: Execute Zabbix40_Server's parameter_generate
    include_tasks: extract.yml
    with_items: "{{ VAR_Zabbix40_Server_linux_extracting_rolename }}"
    loop_control:
      loop_var: outer_item